{
 "title": "Task-2",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Pods Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "count" } },
   "targets": [
    { "expr": "pods_count{}" }
   ]
  },
  {
   "title": "Mem",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "node_memory_MemTotal_bytes{}" },
    {
     "expr": "node_memory_MemAvailable_bytes{}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "node_cpu_seconds_total{}" }
   ]
  }
 ]
}