---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-exp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prom
  template:
    metadata:
      labels:
        app: prom
    spec:
      containers:
        - name: node-exp1
          image: prom/node-exporter
          ports:
            - containerPort: 9100

---
apiVersion: v1
kind: Service
metadata:
  name: node-exp
spec:
  type: ClusterIP
  selector:
    app: prom
  ports:
    - name: nodeexp
      protocol: TCP
      port: 9100
      targetPort: 9100