---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-exp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prom
  template:
    metadata:
      labels:
        app: prom
    spec:
      containers:
        - name: node-exp1
          image: prom/node-exporter
          ports:
            - containerPort: 9100